JobEntity/Models/JobModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace JobEntity.Models
{
    public class JobModel
    {
        public int Job { get; set; }
        public string JobTitle { get; set; }
        public string JobDescription { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime ExpiresAt { get; set; }
    }
}

JobEntity/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JobEntity.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

JobEntity/Controllers/JobController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using JobEntity.Models;
using JobEntity.ViewModel;

namespace JobEntity.Controllers
{
    public class JobController : Controller
    {
        public static JobViewModel vm = new JobViewModel();
        public static List<JobModel> lista = new List<JobModel>();
        // GET: Job
        public ActionResult Index()
        {
            vm.listJob = lista;

            return View(vm);
        }


        // POST: Job/Create
        [HttpPost]
        public JsonResult Create(JobModel md)
        {
            string msj="";
            bool error = true;
            try
            {
                int count = 0;
                if (lista.Count() > 0)
                {
                    JobModel lst = new JobModel();
                    lst = lista.LastOrDefault();
                    count = lst.Job;
                    count = count + 1;
                }
                else
                {
                    count = 0;
                }
                lista.Add(new JobModel() { Job = count, JobTitle = md.JobTitle, JobDescription = md.JobDescription, CreatedAt = DateTime.Now, ExpiresAt = md.ExpiresAt });
                vm.listJob = lista;
                error = true;
            }
            catch
            {
                msj = "A ocurrido un error";
                error = false;
            }

            return Json(new
            {
                success = error,
                mensaje = msj
            });
        }



        // POST: Job/Edit/5
        [HttpPost]
        public ActionResult Edit(JobModel md)
        {
            string msj = "";
            bool error = true;
            try
            {   
                foreach (var mc in lista.Where(x => x.Job == md.Job))
                {
                    mc.JobTitle = md.JobTitle;
                    mc.JobDescription = md.JobDescription;
                    mc.ExpiresAt = md.ExpiresAt;
                }
                vm.listJob = lista;
                error = true;
            }
            catch
            {
                msj = "A ocurrido un error";
                error = false;
            }

            return Json(new
            {
                success = error,
                mensaje = msj
            });
        }


      
        public ActionResult Search(int job)
        {
            JobModel obj = new JobModel();
            string msj = "";
            bool error = true;
            string fecha = "";
            try
            {
                foreach (var mc in lista.Where(x => x.Job == job))
                {
                    obj.Job = job;
                    obj.JobTitle = mc.JobTitle;
                    obj.JobDescription = mc.JobDescription;
                    obj.ExpiresAt =DateTime.Parse( mc.ExpiresAt.ToString());
                    fecha = obj.ExpiresAt.ToString("yyyy-MM-dd");
                }
              
                error = true;
            }
            catch
            {
                msj = "A ocurrido un error";
                error = false;
            }

            return Json(new
            { 
                obj = obj,
                success = error,
                mensaje = msj,
                fecha = fecha
            });
        }




    
        [HttpPost]
        public JsonResult Delete(int job)
        {
            string msj = "";
            bool error = true;
            try
            {

                int index = lista.FindIndex(X => X.Job == job);
                lista.RemoveAt(index);
                vm.listJob = lista;
                error = true;
            }
            catch
            {
                error = false;
                msj = "A ocurrido un error";
            }

            return Json(new
            {
                success = error,
                mensaje = msj
            });
        }
    }
}

JobEntity/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

JobEntity/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

JobEntity/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}


<div class="row">
    <div class="col-md-4">
        <h1>Beatriz Sarai Argueta</h1>
        <h2>Technical Quiz</h2>
    </div>
</div>

JobEntity/Views/Job/Index.cshtml
@model JobEntity.ViewModel.JobViewModel
@{
    ViewBag.Title = "Index";
}

<h2 style="text-align: center;">Jobs</h2>


<nav class="navbar navbar-default">

    <ul class="nav navbar-nav">
        <li class="active"><a onclick=" ModalAgregar()"><i class="fas fa-plus"></i> Job</a></li>
    </ul>
</nav>

<div class="card">
    <div class="card-body">
        <div id="gridJobs">
            @Html.Partial("~/Views/Job/Partials/_jobGrid.cshtml", Model.listJob)
        </div>
    </div>
</div>

@Html.Partial("~/Views/Job/Partials/_addJobModal.cshtml", Model.job)
@Html.Partial("~/Views/Job/Partials/_editJobModal.cshtml", Model.job)

@section Scripts {
    @Html.Partial("~/Views/Job/Partials/_Script.cshtml", Model)
}

JobEntity/Views/Job/Partials/_Script.cshtml
@model JobEntity.ViewModel.JobViewModel

<script type="text/javascript">


    function ModalAgregar() {
        $('#addmodal').modal('show');
    }


     function CreateJob() {
         var JobModel;

         JobModel = {
             JobTitle: $('#job_JobTitle').val(),
             JobDescription: $('#job_JobDescription').val(),
             ExpiresAt: $('#exp').val()
             };


         JobModel.__RequestVerificationToken = $('input[name="__RequestVerificationToken"]').val();

            $.ajax({
                url: '@Url.Action("Create", "Job")',
                data: JobModel,
                type: 'POST',
                contentType: 'application/x-www-form-urlencoded; charset=UTF-8',
                success: function (res) {

                    if (res.success) {
                        location.reload();
                    } else {
                        alert("Error");
                    }
                    $("#loader").hide();
                },
                error: function () {
                }
            });
    }


     function SearchJob(job) {

         $.ajax({
             url: '@Url.Action("Search", "Job")',
             data: { job: job},
                type: 'POST',
                contentType: 'application/x-www-form-urlencoded; charset=UTF-8',
                success: function (res) {

                    if (res.success) {
                        $("#job_Job").val(res.obj.Job);
                        $("#jTitle").val(res.obj.JobTitle);
                        $("#jDescription").val(res.obj.JobDescription);
                        $("#expEdit").val(res.fecha);
                        $('#editmodal').modal('show');
                    } else {
                        alert("Error");
                    }
                    $("#loader").hide();
                },
                error: function () {
                }
            });
    }

       function EditJob() {
         var JobModel;

           JobModel = {
               Job: $("#job_Job").val(),
               JobTitle: $('#jTitle').val(),
               JobDescription: $('#jDescription').val(),
               ExpiresAt: $('#expEdit').val()
             };


         JobModel.__RequestVerificationToken = $('input[name="__RequestVerificationToken"]').val();

            $.ajax({
                url: '@Url.Action("Edit", "Job")',
                data: JobModel,
                type: 'POST',
                contentType: 'application/x-www-form-urlencoded; charset=UTF-8',
                success: function (res) {

                    if (res.success) {
                        location.reload();
                    } else {
                        alert("Error");
                    }
                    $("#loader").hide();
                },
                error: function () {
                }
            });
    }


         function DeleteJob(job) {
      
             $.ajax({
                 url: '@Url.Action("Delete", "Job")',
                 data: { job: job },
                type: 'POST',
                contentType: 'application/x-www-form-urlencoded; charset=UTF-8',
                success: function (res) {

                    if (res.success) {
                        location.reload();
                    } else {
                        alert("Error");
                    }
                    $("#loader").hide();
                },
                error: function () {
                }
            });
    }
</script>

JobEntity/Views/Job/Partials/_addJobModal.cshtml
@model JobEntity.ViewModel.JobViewModel

<div class="modal fade" id="addmodal" role="dialog">
    <div class="modal-dialog" style="width:350px; margin: 0 auto; display:block;">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Add Job</h4>
            </div>
            <div class="modal-body">
                <div class="form-group row" id="divlab">
                    <div class="col-md-12">
                        @Html.LabelFor(model => model.job.JobTitle, labelText: "Title ", htmlAttributes: new { @class = "control-label col-md-auto" })
                        @Html.EditorFor(model => model.job.JobTitle, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.job.JobTitle, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-12">
                        @Html.LabelFor(model => model.job.JobDescription, labelText: "Description ", htmlAttributes: new { @class = "control-label col-md-auto" })
                        @Html.EditorFor(model => model.job.JobDescription, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.job.JobDescription, "", new { @class = "text-danger" })
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-md-12">
                        @Html.LabelFor(model => model.job.ExpiresAt, labelText: "Expires At ", htmlAttributes: new { @class = "control-label col-md-auto" })
                        <input type="date" id="exp" name="exp">
                    </div>
                </div>


                </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-info" onclick="CreateJob()" >Save</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>

JobEntity/Views/Job/Partials/_editJobModal.cshtml
@model JobEntity.ViewModel.JobViewModel

<div class="modal fade" id="editmodal" role="dialog" >
    <div class="modal-dialog" style="width:350px; margin: 0 auto; display:block;">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Edit Job</h4>
            </div>
            <div class="modal-body">
                <div class="form-group row" id="divlab">
                    <div class="col-md-12">
                        @Html.LabelFor(model => model.job.Job, labelText: "Job ", htmlAttributes: new { @class = "control-label col-md-auto" })
                        @Html.EditorFor(model => model.job.Job, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                        @Html.ValidationMessageFor(model => model.job.Job, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group row" id="divlab">
                    <div class="col-md-12">
                        @Html.LabelFor(model => model.job.JobTitle, labelText: "Title ", htmlAttributes: new { @class = "control-label col-md-auto" })
                        @Html.EditorFor(model => model.job.JobTitle, new { htmlAttributes = new { @class = "form-control", id = "jTitle" } })
                        @Html.ValidationMessageFor(model => model.job.JobTitle, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-12">
                        @Html.LabelFor(model => model.job.JobDescription, labelText: "Description ", htmlAttributes: new { @class = "control-label col-md-auto" })
                        @Html.EditorFor(model => model.job.JobDescription, new { htmlAttributes = new { @class = "form-control", id = "jDescription" } })
                        @Html.ValidationMessageFor(model => model.job.JobDescription, "", new { @class = "text-danger" })
                    </div>

                </div>
             
                <div class="form-group row">
                    <div class="col-md-12">
                        @Html.LabelFor(model => model.job.ExpiresAt, labelText: "Expires At ", htmlAttributes: new { @class = "control-label col-md-auto" })
                        <input type="date" id="expEdit" name="expEdit">
                    </div>
                </div>


            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-info" onclick="EditJob()" >Save</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>

JobEntity/Views/Job/Partials/_jobGrid.cshtml
@model IEnumerable<JobEntity.Models.JobModel>


<table class="table table-bordered table-udb table-hover table-responsive-lg">
    <thead>
        <tr>
            <th>
                Job
            </th>
            <th>
              Title
            </th>
            <th>
               Description
            </th>
            <th>
               Created At
            </th>
            <th>
              Expires At
            </th>
          

            @if (Model.Count() > 0)
            {
                <th>Opciones</th>
            }
        </tr>
    </thead>
    @if (Model.Count() > 0)
    {
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Job)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.JobTitle)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.JobDescription)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CreatedAt)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ExpiresAt)
                    </td>
                    <td style="width:155px;">
                        <a class="btn btn-info" data-toggle="tooltip" title="Editar" onclick="SearchJob(@item.Job)">
                            <i class="far fa-edit"></i>
                        </a>

                        <a class="btn btn-danger" href="" data-toggle="tooltip" title="Eliminar" onclick=" DeleteJob(@item.Job)">
                            <i class="fas fa-trash-alt"></i>
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    }

</table>

JobEntity/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Job Entity</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <script src="https://kit.fontawesome.com/3d76dd1928.js" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">

            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Job", "Index", "Job")</li>
                </ul>
            </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>